name: CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions a tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Archive Project
        run: xcodebuild -project ActionOnSwift.xcodeproj -scheme ActionOnSwift -destination 'generic/platform=iOS' -archivePath ../../builds/ActionOnSwift.xcarchive archive
        shell: bash
      
      - name: Export Archive
        run: xcodebuild -exportArchive -archivePath ../../builds/ActionOnSwift.xcarchive -exportPath ../../builds -exportOptionsPlist ../../ExportPlist/ExportOptions_iOS.plist
        shell: bash